CREATE TABLE IF NOT EXISTS SUB_PREMIOS (
    id SERIAL PRIMARY KEY,
    premio_id INTEGER REFERENCES PREMIACOES(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL,
    padrao_grade JSONB,
    ordem_exibicao INTEGER DEFAULT 0,
    realizada BOOLEAN DEFAULT FALSE
);
